/**
 * The microdelta entry. Its public surface preserves the scaffold's Store
 * factory, composing its required host capability at the application boundary.
 * Its project-private `@alpha` surface is the workspace authoring and run path:
 * authoring builders (including keyed collections, gated fanout templates,
 * supplied step slots, forwarded arguments, strict folds and outcome folds),
 * durable workspaces supervised by Run Supervision, the normal, members,
 * strict fold, outcome fold and recovery entry operations with their typed
 * reports, and runtime context lookup; and the operational surface: the
 * external operation handle with operator inspection and settlement, stop
 * control, the writer-wait deadline, the deferral mode, environments with
 * recorded promotion, usage summaries through the caller's injected
 * Accounting port, and the privacy-restricted run events. Context
 * code may use owner contracts directly, never this assembly facade.
 * @packageDocumentation
 */
import { createMemoryStore as createHistoryMemoryStore } from '@microdelta/history';
import type { MemoryStoreOptions, Store } from '@microdelta/history';

import { machine } from './host.js';

/**
 * Create the existing non-durable memory store with Node's detached snapshot
 * capability supplied by assembly.
 * @public
 */
export function createMemoryStore(options: MemoryStoreOptions = {}): Store {
  return createHistoryMemoryStore(machine, options);
}

export {
  DuplicateRowError,
  FingerprintAlgorithmMismatchError,
  InvalidStorePatchError,
  MissingRowError,
} from '@microdelta/history';
export type {
  Divergence,
  FieldRow,
  Fingerprint,
  GenerationPatch,
  GenerationRow,
  GenerationState,
  Identity,
  MemoryStoreOptions,
  Outcome,
  Path,
  RecordedRead,
  ResultKey,
  Store,
  StoreMetadata,
  Subject,
  SubjectPatch,
  SubjectRow,
} from '@microdelta/history';

export {
  authoring,
  sourceOutcome,
  type IAnyTemplateDeclaration,
  type IAuthoring,
  type IAuthoringFamily,
  type ICancelledEntry,
  type IChildResult,
  type ICollectionResult,
  type ICollectionStatus,
  type IComposition,
  type IDeclaredCallHandle,
  type IDerivedArguments,
  type IFailedEntry,
  type IFoldDeclaration,
  type IFoldEntry,
  type IForward,
  type IForwarded,
  type IKeyedMember,
  type IKeyedSnapshot,
  type IKeyingDiagnostic,
  type IKeyingFailure,
  type IMemberBinding,
  type IMemberBuilder,
  type IOutcomeEntry,
  type IOutcomeFoldDeclaration,
  type IPathInput,
  type IPreviousResult,
  type IResultView,
  type ISkippedEntry,
  type ISlotSubject,
  type ISourceOutcome,
  type ISourceOutcomes,
  type IStepDescriptor,
  type IStepSlot,
  type ISucceededEntry,
  type ISuppliedStepDeclaration,
  type ISuppliedStepRegistration,
  type ITrackedHelpers,
  type ITrackedView,
  type IUntrackedRead,
} from './authoring.js';
export {
  ResolutionError,
  SupervisionError,
  WriterBusyError,
  createStopController,
  currentExecution,
  currentRun,
  openWorkspace,
  ordinaryLifecycle,
  stepLifecycle,
  type IAbortSignal,
  type IAttemptUsage,
  type IAdmissionDecision,
  type IAdmissionPolicy,
  type IAdmissionRequest,
  type ICandidateMiss,
  type ICheckOutcome,
  type ICompletedResultReference,
  type ICompleteOutcomeFoldCoverage,
  type IDeferralMode,
  type IDiscoveryReport,
  type IFoldCoverage,
  type IFoldOutcome,
  type IFoldReport,
  type IGateEvidence,
  type IIncompleteOutcomeFoldCoverage,
  type ILifecycleEvent,
  type ILifecyclePhase,
  type IMemberOutcome,
  type IMembersReport,
  type IMembersTarget,
  type IOperationAttribution,
  type IOperationBlock,
  type IOperationEvent,
  type IOperationPhase,
  type IOperationQuantity,
  type IOperationReason,
  type IOperationRemoteState,
  type IOperationRequest,
  type IOperationResponse,
  type IOperationRetryPolicy,
  type IOperationSend,
  type IOperationSettlement,
  type IOperationSettlementRecord,
  type IOperationStatus,
  type IOperationSubject,
  type IOperationUsage,
  type IOperationView,
  type IOrdinaryPhase,
  type IOutcomeFoldCoverage,
  type IOutcomeFoldOutcome,
  type IOutcomeFoldReport,
  type IOutcomeFoldRunOutcome,
  type IPromotionEvidence,
  type IPromotionRecord,
  type IPromotionRequest,
  type IRecoveryResult,
  type IRemoteState,
  type IRequestAttemptStatus,
  type IRequestAttemptView,
  type IRequestOptions,
  type IResolutionErrorCode,
  type IResolutionOutcome,
  type IRunContext,
  type IRunEvent,
  type IRunExecution,
  type IRunObserver,
  type IRunResult,
  type ISendInterruption,
  type ISendPhase,
  type ISendRequest,
  type IStopCause,
  type IStopController,
  type IStopLevel,
  type IStopRequest,
  type IStopState,
  type IStrictFoldOutcome,
  type ISupervisionErrorCode,
  type IUnknownUsage,
  type IUsageFilter,
  type IUsageQuery,
  type IUsageSummary,
  type IWaitEvent,
  type IWorkspace,
  type IWorkspaceAccounting,
  type IWorkspaceOptions,
  type IWorkspaceRun,
  type IWorkspaceRunOptions,
  type IWriterWaitOptions,
} from './workspace.js';
